# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:2scMunnwyAeeoM30hsrJ1OJSEFILegUo4QD02S4FBiO5gaSIHwegv40tykRIAOSPKfFh3GWFVP3wcSZbIvY84nFwTyZIfxUzRhZCKbWCmmQjpVK4oenaX5/b5zd4pXx9blOkM32wNMRSpTw1qrMbL7Z8XfpVma5NSUdT8gqMazFvKkG7YvrLjFeX//6Zkz0aPpOVmwE1ooCYen7SY5hCif2fIzRz5qlPS7hEgmefrg==,iv:F5oB6Y8Hp5bJkzpClZUEhec5nzJqQGFhrC8qYwmJGH8=,tag:8kUaEyOvHuPIjHivvSLogw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16gw89qfpfpnvx5q0kac6443khe9mywxwn4qamd8szuludd7hzaqqu5a5hx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VGZqWGxwQ3o2TkdtcG44
        akp5WTg4YTN1WDlTR1dxd3FiS0dyczNZZ0EwClF3bTdiSmpRQ1VoU251d08wZWFr
        NWhEMnBkQUc5TldvVUswakdSZ0xmckUKLS0tIEFtUU9iSDN1bjhxcCtrRmhOWmM5
        dFoxNEJTclhqdHh1QWo1a1B5MlRtVUUKswRtVGT+tIfOdqdRmEuDNbdHF1q4cOdM
        chnkYdz475PFKomwPQPw5PW1wCpZX+DhbmzoYW9voOIgYRaHU2zECA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-11T16:51:35Z"
  mac: ENC[AES256_GCM,data:1GcUK5n9nHwFLvbfgJRE9P+pkc2GgZgtzI9r8R6vs0hP99QVObjrMyLg349LBDW9Z2s50f8HQJOBQM6YrLmDzhP8ifC5aDH66gHUCR5uaGr8QJs3lCxapsDOY+vA62ZKYTWholFZ5MOrhvNKU2YIxSG+L1D68KWD8na5ab/yvMQ=,iv:F1KabAPmWApI3k+RJnh8/ksBt4YoM4dvYzT7KEcmiyE=,tag:b3VE0d+cFo38FbbCHSn41g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
