---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age16gw89qfpfpnvx5q0kac6443khe9mywxwn4qamd8szuludd7hzaqqu5a5hx"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age16gw89qfpfpnvx5q0kac6443khe9mywxwn4qamd8szuludd7hzaqqu5a5hx"
stores:
  yaml:
    indent: 2
