# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:UK6URdv09m/DH9lmYkkDheYzSnLC+vlAK4D/4O0nFYZASNOTsc6Y4A==,iv:Io8YfSnkzxV0RQh/sFcN6i04WuAUuCf6xNjDjV78aDc=,tag:euVYMNLvfuflGiOInW03XA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16gw89qfpfpnvx5q0kac6443khe9mywxwn4qamd8szuludd7hzaqqu5a5hx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN21nUitYNE9iWkJ1Zjlp
        QllLaDdyb2loK1lXdkZqL3o3SmlJanZYL1RzCjFHdks0YzZ4NlE2R3VCaEdlbWNq
        aWdmdGxTNHVQVDJrRm1DR21reUNoeVEKLS0tIGlzOWI0V2JCVFE1WS9DNFpFaVlp
        aGVUbmhTVW44WnBBL1p1RElmKzN0VDgKklUSjj77qJEd6lgcid6V4wwUOVm/Kvxb
        G/877CCDFjFNkcOlWe7rottzTYjFdTfKTR7qigB+gda4A7uBWvtwhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-11T18:09:12Z"
  mac: ENC[AES256_GCM,data:LmHDPpqzkui9ko1EjWucFKSNVyLaba+x2m/h15B+pWTFczoFLTfJbtJGzITkgDePmmxZ/UtQsMVl0VC230Z98nbguJ7ZIcL6xTDqKyiJnoo32kgzRccxaJflo6NLLap6E4tzw97MkiV2noKxVprGLCScNlURKq0wQ3aLwCRI0qQ=,iv:xTcBw6Rqv/PEnyQe/pCf9e/yr1qWrdSzKkaL9NsElKo=,tag:r2U88s8N306xbZs1U3Hj8w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
