# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0tLZnXGiPEGdtHqciOz4EOm8unLsEPsXhXTn/+Ih6Q70FJF5C34v+g==,iv:moHCagUdUjncy6M/crnsV6rHduLyv2x8KLTuDIxmALw=,tag:b6hb6ISfWQY8beKkq4NMTw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16gw89qfpfpnvx5q0kac6443khe9mywxwn4qamd8szuludd7hzaqqu5a5hx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NFhBRjRVdVJIY0JuWTlF
        RGJ1aEg0ak10MStzazUraTRCOXBZbFpTRVdBCm5MTWJab2EwNFBvNDN4NVBjeTRX
        UkRYTE0zaUtOb3E0UnFpNUJZSzNYdGMKLS0tIEZ1cHh6a3pia0tUYThuV2tMNVNr
        NlJaT1hiUGRiY0w0U2x2LzQxSytjRVkKXYIHMcSINby3FPRSN3e1YPK3D0/GQaMD
        UCNY02P6r46Y8LbBC+WsSOOplkzqGCBoF/L+5KjUT+5Kj5Bh8UrAmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-11T18:09:12Z"
  mac: ENC[AES256_GCM,data:bqL/IAA/wMXC9uWVO8qVLSuLecvDBjGcnoH5WhK6hrWriVXr9vAxdF8FK14nw67jDjPzjjrHccVEFe4V8Dgyg9y4FhlQn3CPXPOtb2EP1BmUHXlZbQ8qmjA/0K+ZUO7Gu+HoxLiyltn15gtyow0MPHq/scoBiKdzYO0f9QBi4+Y=,iv:Y2d3V/3umk+S9VOfdSCVAMnGCHalqoj9H89iYDvENe4=,tag:LdlzIMqtpkGhlBfv+jWvPQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
