# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.20.9:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.20.9"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talosmc1cp"
    ipAddress: "192.168.20.235"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "0e:75:09:7f:62:ae"
        dhcp: false
        addresses:
          - "192.168.20.235/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.9"
  - hostname: "talosmc2cp"
    ipAddress: "192.168.20.249"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "56:b9:39:a9:97:3a"
        dhcp: false
        addresses:
          - "192.168.20.249/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.9"
  - hostname: "talosmc3cp"
    ipAddress: "192.168.20.159"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "c6:d5:e8:64:c2:79"
        dhcp: false
        addresses:
          - "192.168.20.159/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.9"
  - hostname: "talosmc1wk"
    ipAddress: "192.168.20.153"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "1a:61:1d:22:d3:a7"
        dhcp: false
        addresses:
          - "192.168.20.153/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
  - hostname: "talosmc2wk"
    ipAddress: "192.168.20.188"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "96:f3:38:b0:9f:35"
        dhcp: false
        addresses:
          - "192.168.20.188/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
  - hostname: "talosmc3wk"
    ipAddress: "192.168.20.144"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e6:e0:f5:8c:b3:a6"
        dhcp: false
        addresses:
          - "192.168.20.144/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

